name: Resurgo.AI - Simulate deploy

on:
  push:
    branches:
      - main
jobs:
  validate-repository:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Declare RCA skipped - forced push
        if: github.event.forced
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/comments \
            -d '{"body":"**ResurgoAI:** Ignoring forced push. Please push your changes with a regular push."}';

          exit 1

      - if: github.event.repository.private
        name: Declare RCA skipped - private repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/comments \
            -d '{"body":"**ResurgoAI:** the demo RCA workflow can not run on a private repository.\nSet repository to 'Public' and merge changes again, if you would like to run the Root Cause Analysis."}';

          exit 1

  deploy:
    needs: validate-repository
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:

      - name: Add commit comment
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/comments \
            -d '{"body":"**ResurgoAI:** working on this deploy now."}';

            exit 0 # Failure to comment is not a terminal error

      - name: Checkout code in 'before' state
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.before }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Simulate load before deploy
        run: |
          echo "Log for deploy ${{ github.event.before }}..${{ github.event.after }}" > app.log
          pip install -r requirements.txt
          PYTHONPATH=. python tests/user.py # writes logs for 50..100 requests to app.log
          mv app.log ..

      - name: Checkout code in 'afer' state
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.after }}

      - name: Simulate load after deploy
        run: |
          pip install -r requirements.txt
          mv ../app.log .
          PYTHONPATH=. python tests/user.py # writes logs for 50..100 requests to app.log

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: Resurgo.AI-log-${{github.run_id}}-${{github.run_attempt}}
          path: app.log

      - name: Deploy Error Handler
        id: deploy-error-handler
        if: failure() && !cancelled()
        run: |
          echo "happened=true" >> "$GITHUB_OUTPUT"
          curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/comments \
            -d '{"body":"**ResurgoAI:**\nTerminal error occured while attempting to deploy the newest changeset. Unable to run root cause analysis.\nPlease consider these actions:\n* Inspect [workflow run logs](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) for errors.\n* Fix any outstanding errors introduced in this deploy.\n* Deploy the new, correct changeset."}'
          exit 1

  root-cause-analys:
    needs: deploy
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Notify Resurgo orchestrator
        run: |
          # Obtain Github OpenID Connect token as a proof of origin
          # Read more at OpenID Connect (OIDC): https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/about-security-hardening-with-openid-connect
          OICDTOKEN=$( curl -s -H "Authorization: Bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" "${ACTIONS_ID_TOKEN_REQUEST_URL}" -d "{}" | jq -r '.value' );

          curl -s --fail-with-body \
            -X POST \
            -H "Authorization: Bearer ${OICDTOKEN}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "X-Resurgo-Api-Version: 2024-11-17" \
            https://github.resurgo.ai/workflow \
            -d '{
                  "github.repository": "${{github.repository}}",
                  "github.repository_owner": "${{github.repository_owner}}",
                  "github.ref": "${{github.ref}}",
                  "github.run_id": "${{github.run_id}}",
                  "github.run_attempt": "${{github.run_attempt}}",
                  "github.sha": "${{github.sha}}"
                }'

      - name: Add commit comment
        run: |
          curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/comments \
            -d '{"body":"**ResurgoAI:**\nUploaded log as [Resurgo.AI-log-${{github.run_id}}-${{github.run_attempt}}](${{ steps.artifact-upload-step.outputs.artifact-url}}) and alerted the orchestrator.\nWaiting for the worker to pick this job."}';

            exit 0 # Failure to comment is not a terminal error

      - name: RCA Error Handler
        id: deploy-error
        if: failure() && !cancelled() && steps.deploy-error-handler.outputs.happened != 'true'
        run: |
          curl -s \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{github.api_url}}/repos/${{github.repository}}/commits/${{github.sha}}/comments \
            -d '{"body":"**ResurgoAI:**\nTerminal error occured while attempting to initiate Root Cause Analysis (RCA).\nThere will be no followup for this deploy."}'
